export const mockProducts = [
  {
    id: '1',
    slug: 'linen-midi-dress',
    title: 'Linen Midi Dress',
    price: 1200,
    currency: 'MDL',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80',
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Beige', 'Navy'],
    materials: 'Made from 100% European linen. Lightweight and breathable.',
    care: 'Machine wash cold. Hang dry. Iron on medium heat.',
    availableInShowroom: true,
    isNew: true,
  },
  {
    id: '2',
    slug: 'silk-blouse',
    title: 'Silk Blouse',
    price: 890,
    currency: 'MDL',
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&q=80',
    category: 'tops',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'Black'],
    materials: '100% Mulberry silk. Soft and luxurious.',
    care: 'Dry clean only.',
    availableInShowroom: true,
  },
  {
    id: '3',
    slug: 'wool-tailored-pants',
    title: 'Wool Tailored Pants',
    price: 1450,
    currency: 'MDL',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80',
    category: 'bottoms',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Camel'],
    materials: 'Italian wool blend. Perfect drape and structure.',
    care: 'Dry clean recommended.',
    availableInShowroom: false,
    onSale: true,
  },
  {
    id: '4',
    slug: 'cashmere-coat',
    title: 'Cashmere Coat',
    price: 3200,
    currency: 'MDL',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80',
    category: 'outerwear',
    sizes: ['S', 'M', 'L'],
    colors: ['Camel', 'Black'],
    materials: '100% Italian cashmere. Timeless elegance.',
    care: 'Professional dry clean only.',
    availableInShowroom: true,
    isNew: true,
  },
  {
    id: '5',
    slug: 'cotton-shirt-dress',
    title: 'Cotton Shirt Dress',
    price: 950,
    currency: 'MDL',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80',
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Navy'],
    materials: 'Organic cotton poplin. Crisp and comfortable.',
    care: 'Machine wash cold. Tumble dry low.',
    availableInShowroom: true,
  },
  {
    id: '6',
    slug: 'knit-sweater',
    title: 'Merino Wool Sweater',
    price: 1100,
    currency: 'MDL',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80',
    category: 'tops',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Cream', 'Charcoal', 'Rust'],
    materials: 'Extra-fine merino wool. Soft and warm.',
    care: 'Hand wash cold or dry clean.',
    availableInShowroom: false,
  },
];

export const lookbookImages = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&q=80',
    title: 'Spring/Summer 2024',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&q=80',
    title: 'Urban Elegance',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1200&q=80',
    title: 'Timeless Classics',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=1200&q=80',
    title: 'Modern Minimalism',
  },
];
